#!/bin/bash


for i in `seq 0 1`;
do
    state=`/opt/dell/srvadmin/bin/omreport storage pdisk controller=0 pdisk=0:1:${i} |awk '/^State/ {print $3}'`
    if [ "$state" == "" ]; then
        state=`/opt/dell/srvadmin/bin/omreport storage pdisk controller=0 pdisk=0:0:${i} |awk '/^State/ {print $3}'`
    fi
    if [ "$state" != "Online" ]; then
        echo "Server contains an OS drive that is in $state state";
        exit 1
    fi
done
exit 0
